name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: npm run all
        run: |
          npm install
          npm run all
      - name: run action.yml
        uses: ./
        with:
          milliseconds: 1000
